{% set name = "simplematch" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simplematch-{{ version }}.tar.gz
  sha256: 55a77278b3d0686cb38e3ffe5a326a5f59c2995f1ba1fa1a4f68872c17caf4cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0

test:
  imports:
    - simplematch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tfeldmann/simplematch
  summary: Minimal, super readable string pattern matching.
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
